//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISTE340ConsumeServices.serviceBeer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://server/", ConfigurationName="serviceBeer.Beer")]
    public interface Beer {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getMethodsRequest", ReplyAction="http://server/Beer/getMethodsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ISTE340ConsumeServices.serviceBeer.getMethodsResponse getMethods(ISTE340ConsumeServices.serviceBeer.getMethodsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getMethodsRequest", ReplyAction="http://server/Beer/getMethodsResponse")]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getMethodsResponse> getMethodsAsync(ISTE340ConsumeServices.serviceBeer.getMethodsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/HelloWorldRequest", ReplyAction="http://server/Beer/HelloWorldResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ISTE340ConsumeServices.serviceBeer.HelloWorldResponse HelloWorld(ISTE340ConsumeServices.serviceBeer.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/HelloWorldRequest", ReplyAction="http://server/Beer/HelloWorldResponse")]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.HelloWorldResponse> HelloWorldAsync(ISTE340ConsumeServices.serviceBeer.HelloWorldRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getCheapestRequest", ReplyAction="http://server/Beer/getCheapestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ISTE340ConsumeServices.serviceBeer.getCheapestResponse getCheapest(ISTE340ConsumeServices.serviceBeer.getCheapestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getCheapestRequest", ReplyAction="http://server/Beer/getCheapestResponse")]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getCheapestResponse> getCheapestAsync(ISTE340ConsumeServices.serviceBeer.getCheapestRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getCostliestRequest", ReplyAction="http://server/Beer/getCostliestResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ISTE340ConsumeServices.serviceBeer.getCostliestResponse getCostliest(ISTE340ConsumeServices.serviceBeer.getCostliestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getCostliestRequest", ReplyAction="http://server/Beer/getCostliestResponse")]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getCostliestResponse> getCostliestAsync(ISTE340ConsumeServices.serviceBeer.getCostliestRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getPriceRequest", ReplyAction="http://server/Beer/getPriceResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ISTE340ConsumeServices.serviceBeer.getPriceResponse getPrice(ISTE340ConsumeServices.serviceBeer.getPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getPriceRequest", ReplyAction="http://server/Beer/getPriceResponse")]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getPriceResponse> getPriceAsync(ISTE340ConsumeServices.serviceBeer.getPriceRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getBeersRequest", ReplyAction="http://server/Beer/getBeersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ISTE340ConsumeServices.serviceBeer.getBeersResponse getBeers(ISTE340ConsumeServices.serviceBeer.getBeersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://server/Beer/getBeersRequest", ReplyAction="http://server/Beer/getBeersResponse")]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getBeersResponse> getBeersAsync(ISTE340ConsumeServices.serviceBeer.getBeersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMethods", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getMethodsRequest {
        
        public getMethodsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMethodsResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getMethodsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getMethodsResponse() {
        }
        
        public getMethodsResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class HelloWorldRequest {
        
        public HelloWorldRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCheapest", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getCheapestRequest {
        
        public getCheapestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCheapestResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getCheapestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getCheapestResponse() {
        }
        
        public getCheapestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCostliest", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getCostliestRequest {
        
        public getCostliestRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCostliestResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getCostliestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public getCostliestResponse() {
        }
        
        public getCostliestResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPrice", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getPriceRequest() {
        }
        
        public getPriceRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getPriceResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double @return;
        
        public getPriceResponse() {
        }
        
        public getPriceResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBeers", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getBeersRequest {
        
        public getBeersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getBeersResponse", WrapperNamespace="http://server/", IsWrapped=true)]
    public partial class getBeersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://server/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] @return;
        
        public getBeersResponse() {
        }
        
        public getBeersResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BeerChannel : ISTE340ConsumeServices.serviceBeer.Beer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BeerClient : System.ServiceModel.ClientBase<ISTE340ConsumeServices.serviceBeer.Beer>, ISTE340ConsumeServices.serviceBeer.Beer {
        
        public BeerClient() {
        }
        
        public BeerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BeerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BeerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BeerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISTE340ConsumeServices.serviceBeer.getMethodsResponse ISTE340ConsumeServices.serviceBeer.Beer.getMethods(ISTE340ConsumeServices.serviceBeer.getMethodsRequest request) {
            return base.Channel.getMethods(request);
        }
        
        public string[] getMethods() {
            ISTE340ConsumeServices.serviceBeer.getMethodsRequest inValue = new ISTE340ConsumeServices.serviceBeer.getMethodsRequest();
            ISTE340ConsumeServices.serviceBeer.getMethodsResponse retVal = ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getMethods(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getMethodsResponse> ISTE340ConsumeServices.serviceBeer.Beer.getMethodsAsync(ISTE340ConsumeServices.serviceBeer.getMethodsRequest request) {
            return base.Channel.getMethodsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getMethodsResponse> getMethodsAsync() {
            ISTE340ConsumeServices.serviceBeer.getMethodsRequest inValue = new ISTE340ConsumeServices.serviceBeer.getMethodsRequest();
            return ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getMethodsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISTE340ConsumeServices.serviceBeer.HelloWorldResponse ISTE340ConsumeServices.serviceBeer.Beer.HelloWorld(ISTE340ConsumeServices.serviceBeer.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ISTE340ConsumeServices.serviceBeer.HelloWorldRequest inValue = new ISTE340ConsumeServices.serviceBeer.HelloWorldRequest();
            ISTE340ConsumeServices.serviceBeer.HelloWorldResponse retVal = ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).HelloWorld(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.HelloWorldResponse> ISTE340ConsumeServices.serviceBeer.Beer.HelloWorldAsync(ISTE340ConsumeServices.serviceBeer.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.HelloWorldResponse> HelloWorldAsync() {
            ISTE340ConsumeServices.serviceBeer.HelloWorldRequest inValue = new ISTE340ConsumeServices.serviceBeer.HelloWorldRequest();
            return ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISTE340ConsumeServices.serviceBeer.getCheapestResponse ISTE340ConsumeServices.serviceBeer.Beer.getCheapest(ISTE340ConsumeServices.serviceBeer.getCheapestRequest request) {
            return base.Channel.getCheapest(request);
        }
        
        public string getCheapest() {
            ISTE340ConsumeServices.serviceBeer.getCheapestRequest inValue = new ISTE340ConsumeServices.serviceBeer.getCheapestRequest();
            ISTE340ConsumeServices.serviceBeer.getCheapestResponse retVal = ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getCheapest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getCheapestResponse> ISTE340ConsumeServices.serviceBeer.Beer.getCheapestAsync(ISTE340ConsumeServices.serviceBeer.getCheapestRequest request) {
            return base.Channel.getCheapestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getCheapestResponse> getCheapestAsync() {
            ISTE340ConsumeServices.serviceBeer.getCheapestRequest inValue = new ISTE340ConsumeServices.serviceBeer.getCheapestRequest();
            return ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getCheapestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISTE340ConsumeServices.serviceBeer.getCostliestResponse ISTE340ConsumeServices.serviceBeer.Beer.getCostliest(ISTE340ConsumeServices.serviceBeer.getCostliestRequest request) {
            return base.Channel.getCostliest(request);
        }
        
        public string getCostliest() {
            ISTE340ConsumeServices.serviceBeer.getCostliestRequest inValue = new ISTE340ConsumeServices.serviceBeer.getCostliestRequest();
            ISTE340ConsumeServices.serviceBeer.getCostliestResponse retVal = ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getCostliest(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getCostliestResponse> ISTE340ConsumeServices.serviceBeer.Beer.getCostliestAsync(ISTE340ConsumeServices.serviceBeer.getCostliestRequest request) {
            return base.Channel.getCostliestAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getCostliestResponse> getCostliestAsync() {
            ISTE340ConsumeServices.serviceBeer.getCostliestRequest inValue = new ISTE340ConsumeServices.serviceBeer.getCostliestRequest();
            return ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getCostliestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISTE340ConsumeServices.serviceBeer.getPriceResponse ISTE340ConsumeServices.serviceBeer.Beer.getPrice(ISTE340ConsumeServices.serviceBeer.getPriceRequest request) {
            return base.Channel.getPrice(request);
        }
        
        public double getPrice(string arg0) {
            ISTE340ConsumeServices.serviceBeer.getPriceRequest inValue = new ISTE340ConsumeServices.serviceBeer.getPriceRequest();
            inValue.arg0 = arg0;
            ISTE340ConsumeServices.serviceBeer.getPriceResponse retVal = ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getPrice(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getPriceResponse> ISTE340ConsumeServices.serviceBeer.Beer.getPriceAsync(ISTE340ConsumeServices.serviceBeer.getPriceRequest request) {
            return base.Channel.getPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getPriceResponse> getPriceAsync(string arg0) {
            ISTE340ConsumeServices.serviceBeer.getPriceRequest inValue = new ISTE340ConsumeServices.serviceBeer.getPriceRequest();
            inValue.arg0 = arg0;
            return ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getPriceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ISTE340ConsumeServices.serviceBeer.getBeersResponse ISTE340ConsumeServices.serviceBeer.Beer.getBeers(ISTE340ConsumeServices.serviceBeer.getBeersRequest request) {
            return base.Channel.getBeers(request);
        }
        
        public string[] getBeers() {
            ISTE340ConsumeServices.serviceBeer.getBeersRequest inValue = new ISTE340ConsumeServices.serviceBeer.getBeersRequest();
            ISTE340ConsumeServices.serviceBeer.getBeersResponse retVal = ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getBeers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getBeersResponse> ISTE340ConsumeServices.serviceBeer.Beer.getBeersAsync(ISTE340ConsumeServices.serviceBeer.getBeersRequest request) {
            return base.Channel.getBeersAsync(request);
        }
        
        public System.Threading.Tasks.Task<ISTE340ConsumeServices.serviceBeer.getBeersResponse> getBeersAsync() {
            ISTE340ConsumeServices.serviceBeer.getBeersRequest inValue = new ISTE340ConsumeServices.serviceBeer.getBeersRequest();
            return ((ISTE340ConsumeServices.serviceBeer.Beer)(this)).getBeersAsync(inValue);
        }
    }
}
